# Generated by Django 4.0.5 on 2023-02-03 10:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0002_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('36', 36), ('37', 37), ('38', 38), ('39', 39)], max_length=11),
        ),
    ]
