# Generated by Django 4.0.5 on 2023-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0002_subscription_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('WH', 'white'), ('TN', 'tan'), ('RD', 'red'), ('BW', 'brown'), ('BK', 'black')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='fashionStore.color'),
        ),
    ]
