# Generated by Django 4.0.5 on 2023-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0003_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('WHITE', 'white'), ('TAN', 'tan'), ('RED', 'red'), ('BROWN', 'brown'), ('BLACK', 'black')], max_length=5),
        ),
    ]
