# Generated by Django 4.0.5 on 2023-03-03 10:48

from django.db import migrations, models
import fashionStore.models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0004_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=fashionStore.models.generate_transaction_id, editable=False, max_length=100),
        ),
    ]
