# Generated by Django 4.0.5 on 2023-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0005_remove_product_trending_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
