# Generated by Django 4.0.5 on 2023-02-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0008_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['id']},
        ),
    ]
